### ISSUE TITLE
version 1.5 has bug when I packaged my project to jar file.

### ISSUE THREAD

**Issue by overlordsnyt** [eclecticlogic/pedal-dialect#2]
when I use setting as this:
<groupId>com.eclecticlogic</groupId>
<artifactId>pedal-dialect</artifactId>
<version>1.5.0</version>
It can throw the exception when I packaged my project to jar file.
But it no problem when I debug my code.
When I switch the version to 1.4.0,all thing would run correctly.
So this problem must be in the version 1.5.0 .

cmd print follow info:

2018-10-08 16:08:23.496 ERROR 15284 --- [nio-8088-exec-1] o.a.c.c.C.[.[.[.[.s.c.JerseyConfig]      : Servlet.service() for servlet [com.synyi.config.JerseyConfig] in context with path [] threw exception [org.joor.ReflectException: Compilation error: /com/eclecticlogic/pedal/dialect/postgresql/extractor/MetaDataInstanceEntity$Extractor_1.java:3: 错误: 找不到 符号
public class MetaDataInstanceEntity$Extractor_1 extends com.eclecticlogic.pedal.dialect.postgresql.AbstractCopyExtractor {
^
符号:   类 AbstractCopyExtractor
位置: 程序包 com.eclecticlogic.pedal.dialect.postgresql
/com/eclecticlogic/pedal/dialect/postgresql/extractor/MetaDataInstanceEntity$Extractor_1.java:11: 错误: 程序包com.synyi.infrastructure.persistence.hibernate.entities不存在
com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity typed = (com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity)entity;
^
/com/eclecticlogic/pedal/dialect/postgresql/extractor/MetaDataInstanceEntity$Extractor_1.java:11: 错误: 程序包com.synyi.infrastructure.persistence.hibernate.entities不存在
com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity typed = (com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity)entity;
^
3 个错误
] with root cause
org.joor.ReflectException: Compilation error: /com/eclecticlogic/pedal/dialect/postgresql/extractor/MetaDataInstanceEntity$Extractor_1.java:3: 错误: 找不到符号
public class MetaDataInstanceEntity$Extractor_1 extends com.eclecticlogic.pedal.dialect.postgresql.AbstractCopyExtractor {
^
符号:   类 AbstractCopyExtractor
位置: 程序包 com.eclecticlogic.pedal.dialect.postgresql
/com/eclecticlogic/pedal/dialect/postgresql/extractor/MetaDataInstanceEntity$Extractor_1.java:11: 错误: 程序包com.synyi.infrastructure.persistence.hibernate.entities不存在
com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity typed = (com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity)entity;
^
/com/eclecticlogic/pedal/dialect/postgresql/extractor/MetaDataInstanceEntity$Extractor_1.java:11: 错误: 程序包com.synyi.infrastructure.persistence.hibernate.entities不存在
com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity typed = (com.synyi.infrastructure.persistence.hibernate.entities.MetaDataInstanceEntity)entity;
^
3 个错误
    at org.joor.Compile.compile(Compile.java:65) ~[joor-java-8-0.9.9.jar!/:na]
    at org.joor.Reflect.compile(Reflect.java:77) ~[joor-java-8-0.9.9.jar!/:na]
    at com.eclecticlogic.pedal.dialect.postgresql.CopyCommandImpl.getExtractor(CopyCommandImpl.java:131) ~[pedal-dialect-1.5.0.jar!/:na]
    at com.eclecticlogic.pedal.dialect.postgresql.CopyCommandImpl.lambda$_insert$0(CopyCommandImpl.java:66) ~[pedal-dialect-1.5.0.jar!/:na]
    at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1719) ~[na:na]
    at com.eclecticlogic.pedal.dialect.postgresql.CopyCommandImpl._insert(CopyCommandImpl.java:66) ~[pedal-dialect-1.5.0.jar!/:na]
    at com.eclecticlogic.pedal.dialect.postgresql.CopyCommandImpl.insert(CopyCommandImpl.java:59) ~[pedal-dialect-1.5.0.jar!/:na]

**Comment by eclecticlogic** [comment]
Please try version 1.5.1. This is an issue with the JOOR runtime compilation library and I've worked around it.

**Comment by overlordsnyt** [comment]
It worked,thank you for your surpassing work.
